import builtins from 'builtin-modules';
import esbuild from 'esbuild';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;
const prod = process.argv[2] === 'production';
const watch = false;

const context = await esbuild.context({
  banner: {
    js: banner
  },
  outfile: 'dist/main.js',
  entryPoints: ['./src/main.ts'],
  bundle: true,
  target: 'es2017',
  format: 'cjs',
  logLevel: 'debug',
  sourcemap: prod ? false : 'inline',
  minify: prod ? true : false,
  treeShaking: true,
  external: [
    'obsidian',
    'electron',
    'codemirror',
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/commands',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/view',
    ...builtins
  ]
});

try {
  await context.rebuild();
  console.log('Build finished!');

  if (watch) {
    await context.watch();
  }

  process.exit(0);
} catch (error) {
  console.error('Failed to build.');
  process.exit(1);
}
